# Generated by Django 2.2.5 on 2021-05-02 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='engine_info',
            fields=[
                ('engine', models.IntegerField(primary_key=True, serialize=False)),
                ('aircraft', models.CharField(max_length=8)),
                ('left_right', models.CharField(blank=True, max_length=5)),
                ('flight_day', models.IntegerField(blank=True, null=True)),
                ('flight_time', models.FloatField(blank=True, null=True)),
                ('run_time', models.FloatField(blank=True, null=True)),
                ('c1_cycle', models.IntegerField(blank=True, null=True)),
                ('flight_cycle', models.IntegerField(blank=True, null=True)),
                ('engine_starts', models.IntegerField(blank=True, null=True)),
                ('reverse_cycle', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FTSI2IPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date', models.CharField(blank=True, max_length=100)),
                ('current_type', models.CharField(blank=True, max_length=30)),
                ('next_target', models.CharField(blank=True, max_length=30)),
                ('residual_times', models.IntegerField(blank=True, null=True)),
                ('active_status', models.BooleanField()),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.engine_info')),
            ],
        ),
        migrations.CreateModel(
            name='ftsi_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftsi_num', models.CharField(max_length=20)),
                ('rev', models.CharField(max_length=5)),
                ('ftsi_title', models.CharField(blank=True, max_length=200)),
                ('statement', models.CharField(blank=True, max_length=500)),
                ('active_status', models.BooleanField()),
                ('dep_type', models.CharField(choices=[('OTHER', 'On condition'), ('FD', 'Up to flight day'), ('FH', 'Up to flight hour'), ('EH', 'Up to engine hour'), ('CC', 'Up to C1 cycle'), ('DATE', 'Up to date'), ('FC', 'Up to flight cycle'), ('ES', 'Up to engine starts'), ('RC', 'Up to reverse cycle'), ('CUS', 'Customize')], max_length=30)),
                ('period', models.CharField(blank=True, max_length=30)),
                ('total_times', models.IntegerField(blank=True, null=True)),
                ('ips', models.ManyToManyField(through='common.FTSI2IPS', to='common.engine_info')),
            ],
            options={
                'db_table': 'common_ftsi_info',
                'unique_together': {('ftsi_num', 'rev')},
            },
        ),
        migrations.CreateModel(
            name='historyrecord_ftsi_modify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('modify_type', models.CharField(max_length=20)),
                ('ftsi_num', models.CharField(max_length=20)),
                ('rev', models.CharField(max_length=5)),
                ('ftsi_title', models.CharField(blank=True, max_length=200)),
                ('statement', models.CharField(blank=True, max_length=500)),
                ('effect_change', models.BooleanField(blank=True, null=True)),
                ('monitor_change', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historyrecord_ftsiModify',
            },
        ),
        migrations.CreateModel(
            name='historyrecord_task_submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('aircraft', models.CharField(max_length=8)),
                ('engine', models.IntegerField()),
                ('ftsi_info', models.CharField(blank=True, max_length=200)),
                ('implement_info', models.CharField(blank=True, max_length=100)),
                ('next_step', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'historyrecord_taskSubmit',
            },
        ),
        migrations.CreateModel(
            name='trigger_relationship',
            fields=[
                ('exciter_FTSI', models.CharField(max_length=20)),
                ('response_FTSI', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='customized_type',
            fields=[
                ('ftsi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='common.ftsi_info')),
                ('trigger_factor', models.CharField(blank=True, choices=[('NA', 'No active item'), ('TDATE', 'Active by date'), ('TFTSI', 'Active by FTSI')], max_length=30)),
                ('trigger_para', models.CharField(blank=True, max_length=30)),
                ('dep_type1', models.CharField(max_length=30)),
                ('period1', models.CharField(blank=True, max_length=30)),
                ('total_times1', models.IntegerField(blank=True, null=True)),
                ('dep_type2', models.CharField(max_length=30)),
                ('period2', models.CharField(blank=True, max_length=30)),
                ('total_times2', models.IntegerField(blank=True, null=True)),
                ('dep_type3', models.CharField(max_length=30)),
                ('period3', models.CharField(blank=True, max_length=30)),
                ('total_times3', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='historyrecord_engine_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('engine', models.IntegerField()),
                ('aircraft', models.CharField(max_length=8)),
                ('left_right', models.CharField(blank=True, max_length=5)),
                ('flight_day', models.IntegerField(blank=True, null=True)),
                ('flight_time', models.FloatField(blank=True, null=True)),
                ('run_time', models.FloatField(blank=True, null=True)),
                ('c1_cycle', models.IntegerField(blank=True, null=True)),
                ('flight_cycle', models.IntegerField(blank=True, null=True)),
                ('engine_starts', models.IntegerField(blank=True, null=True)),
                ('reverse_cycle', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historyrecord_engineInfo',
                'unique_together': {('date', 'engine')},
            },
        ),
        migrations.CreateModel(
            name='ftsi_number_issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.TextField(blank=True, max_length=20)),
                ('logged_date', models.TextField(blank=True, max_length=40)),
                ('type', models.TextField(blank=True, null=True)),
                ('ftsi_no', models.TextField(blank=True, max_length=10)),
                ('revision', models.TextField(blank=True, max_length=5)),
                ('ftsi_title', models.CharField(blank=True, max_length=200)),
                ('statement', models.CharField(blank=True, max_length=500)),
                ('impact_ips', models.TextField(blank=True, max_length=100)),
                ('issue_date', models.TextField(blank=True, max_length=40)),
                ('action_type', models.TextField(blank=True, max_length=10)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'common_ftsi_number_issue',
                'unique_together': {('ftsi_no', 'revision')},
            },
        ),
        migrations.CreateModel(
            name='FTSI_implement_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.TextField(blank=True, max_length=40)),
                ('logged_date', models.TextField(blank=True, max_length=40)),
                ('identification', models.IntegerField(blank=True, null=True)),
                ('document_type', models.TextField(blank=True, max_length=20)),
                ('document_no', models.TextField(blank=True, max_length=10)),
                ('document_revision', models.TextField(blank=True, max_length=5)),
                ('implement_status', models.BooleanField()),
            ],
            options={
                'db_table': 'common_ftsi_implement_list',
                'unique_together': {('activity_date', 'identification', 'document_no')},
            },
        ),
        migrations.AddField(
            model_name='ftsi2ips',
            name='ftsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.ftsi_info'),
        ),
    ]
