# Generated by Django 2.2.5 on 2021-05-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightTestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_day', models.TextField(blank=True, null=True)),
                ('msn', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('squawks', models.TextField(blank=True, null=True)),
                ('esn1', models.TextField(blank=True, null=True)),
                ('esn1_runtime', models.TextField(blank=True, null=True)),
                ('esn1_cycle', models.TextField(blank=True, null=True)),
                ('esn2', models.TextField(blank=True, null=True)),
                ('esn2_runtime', models.TextField(blank=True, null=True)),
                ('esn2_cycle', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('tr_deployed', models.TextField(blank=True, null=True)),
                ('comac_no', models.TextField(blank=True, null=True)),
                ('flight_hour', models.TextField(blank=True, null=True)),
                ('flight_cycle', models.TextField(blank=True, null=True)),
                ('test_date', models.TextField(blank=True, null=True)),
                ('flight_time', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'flight_test_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PoTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('po_field', models.FloatField(blank=True, db_column='PO#', null=True)),
                ('po_version', models.FloatField(blank=True, db_column='PO version', null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('part_number', models.TextField(blank=True, db_column='Part number', null=True)),
                ('series_number', models.TextField(blank=True, db_column='Series number', null=True)),
                ('supplier', models.TextField(blank=True, db_column='Supplier', null=True)),
                ('ms_information_gl_date', models.TextField(blank=True, db_column='MS Information/GL Date', null=True)),
                ('shipment_date', models.TextField(blank=True, db_column='Shipment Date', null=True)),
                ('awb_no_field', models.TextField(blank=True, db_column='AWB No.', null=True)),
                ('actually_arrived_date', models.TextField(blank=True, db_column='Actually Arrived Date', null=True)),
                ('qty_required', models.FloatField(blank=True, db_column='Qty required', null=True)),
                ('qty_received', models.FloatField(blank=True, db_column='Qty Received', null=True)),
                ('gap', models.FloatField(blank=True, db_column='Gap', null=True)),
                ('po_release_date', models.TextField(blank=True, db_column='PO Release Date', null=True)),
                ('remarks', models.TextField(blank=True, db_column='Remarks', null=True)),
                ('cfm_po_field', models.TextField(blank=True, db_column='CFM PO#', null=True)),
            ],
            options={
                'db_table': 'po_tracker',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScDailyMiReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_date', models.TextField(blank=True, null=True)),
                ('activity_date', models.TextField(blank=True, null=True)),
                ('logged_date', models.TextField(blank=True, null=True)),
                ('ac_msn', models.TextField(blank=True, null=True)),
                ('mi_job_no', models.TextField(blank=True, null=True)),
                ('task_interval', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sc_daily_mi_report',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScFtsiTracking',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('logged_date', models.TextField(blank=True, null=True)),
                ('ftsi_no', models.TextField(blank=True, null=True)),
                ('revision', models.TextField(blank=True, null=True)),
                ('ftsi_title', models.TextField(blank=True, null=True)),
                ('impact_ips', models.TextField(blank=True, null=True)),
                ('compliance', models.TextField(blank=True, null=True)),
                ('issue_date', models.TextField(blank=True, null=True)),
                ('entry_no', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sc_ftsi_tracking',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScIpsInformationOnly',
            fields=[
                ('activity_date', models.TextField(blank=True, null=True)),
                ('logged_date', models.TextField(blank=True, null=True)),
                ('ac_msn', models.TextField(blank=True, null=True)),
                ('ac_position', models.TextField(blank=True, null=True)),
                ('identification', models.TextField(blank=True, null=True)),
                ('document_type', models.TextField(blank=True, null=True)),
                ('document_no', models.TextField(blank=True, null=True)),
                ('document_revision', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sc_ips_information_only',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ToscTrackingEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esn', models.TextField(blank=True, null=True)),
                ('flight_time', models.FloatField(blank=True, null=True)),
                ('flight_cycle', models.FloatField(blank=True, null=True)),
                ('flight_day', models.BigIntegerField(blank=True, null=True)),
                ('c1_cycle', models.BigIntegerField(blank=True, null=True)),
                ('run_time', models.FloatField(blank=True, null=True)),
                ('starts', models.FloatField(blank=True, null=True)),
                ('failed_starts', models.FloatField(blank=True, null=True)),
                ('inflight_c1_cycle', models.BigIntegerField(blank=True, null=True)),
                ('inflight_run_time', models.FloatField(blank=True, null=True)),
                ('last_msn', models.TextField(blank=True, null=True)),
                ('last_position', models.TextField(blank=True, null=True)),
                ('last_test_type', models.TextField(blank=True, null=True)),
                ('current_installation', models.TextField(blank=True, null=True)),
                ('reverse_cycle', models.TextField(blank=True, null=True)),
                ('last_msn_time', models.TextField(blank=True, null=True)),
                ('last_msn_cycle', models.TextField(blank=True, null=True)),
                ('last_msn_day', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tosc_tracking_engine',
                'managed': True,
            },
        ),
    ]
