# Generated by Django 2.2.5 on 2021-05-02 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='monitor_para',
            fields=[
                ('owner', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('w_FD', models.IntegerField()),
                ('w_FH', models.IntegerField()),
                ('w_EH', models.IntegerField()),
                ('w_CC', models.IntegerField()),
                ('w_FC', models.IntegerField()),
                ('w_ES', models.IntegerField()),
                ('w_RC', models.IntegerField()),
                ('w_DATE', models.IntegerField()),
                ('a_FD', models.IntegerField()),
                ('a_FH', models.IntegerField()),
                ('a_EH', models.IntegerField()),
                ('a_CC', models.IntegerField()),
                ('a_FC', models.IntegerField()),
                ('a_ES', models.IntegerField()),
                ('a_RC', models.IntegerField()),
                ('a_DATE', models.IntegerField()),
                ('p_FD', models.IntegerField()),
                ('p_FH', models.IntegerField()),
                ('p_EH', models.IntegerField()),
                ('p_CC', models.IntegerField()),
                ('p_FC', models.IntegerField()),
                ('p_ES', models.IntegerField()),
                ('p_RC', models.IntegerField()),
                ('p_DATE', models.IntegerField()),
            ],
            options={
                'db_table': 'userOpt_monitor_para',
            },
        ),
        migrations.CreateModel(
            name='userCacheEngineInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('cacheDate', models.CharField(max_length=20)),
                ('engine', models.IntegerField()),
                ('aircraft', models.CharField(max_length=8)),
                ('left_right', models.CharField(blank=True, max_length=5)),
                ('flight_day', models.IntegerField(blank=True, null=True)),
                ('flight_time', models.FloatField(blank=True, null=True)),
                ('run_time', models.FloatField(blank=True, null=True)),
                ('c1_cycle', models.IntegerField(blank=True, null=True)),
                ('flight_cycle', models.IntegerField(blank=True, null=True)),
                ('engine_starts', models.IntegerField(blank=True, null=True)),
                ('reverse_cycle', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'userOpt_engineInfo',
                'unique_together': {('username', 'engine')},
            },
        ),
        migrations.CreateModel(
            name='userCacheFTSI2IPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftsi_id', models.IntegerField()),
                ('last_date', models.CharField(blank=True, max_length=100)),
                ('current_type', models.CharField(blank=True, max_length=30)),
                ('next_target', models.CharField(blank=True, max_length=300)),
                ('residual_times', models.IntegerField(blank=True, null=True)),
                ('active_status', models.BooleanField()),
                ('cache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userOpt.userCacheEngineInfo')),
            ],
            options={
                'db_table': 'userOpt_ftsi2ips',
            },
        ),
    ]
